### ISSUE TITLE
set region dynamically depending on region

### ISSUE THREAD

**Issue by karlderkaefer** [karlderkaefer/argocd-ecr-updater#13]
The registry id contains the region.
```
123456789012.dkr.ecr.eu-central-1.amazonaws.com
```
when getting the token the region must match the repository
```
aws ecr get-login-password --region eu-central-1
```
Ideally we parse this info out of existing secret definition before
```
apiVersion: v1
kind: Secret
stringData:
  enableOCI: "true"
  name: helm-ecr
  type: helm
  url: 123456789012.dkr.ecr.eu-central-1.amazonaws.com
```
